export const elements = {
  statusMessage: document.getElementById("statusMessage"),
  sourceSite: document.getElementById("sourceSite"),
  sourceSiteValue: document.getElementById("sourceSiteValue"),
  imageList: document.getElementById("imageList"),
  paginationPanel: document.getElementById("paginationPanel"),
  paginationInfo: document.getElementById("paginationInfo"),
  paginationPrevButton: document.getElementById("paginationPrevButton"),
  paginationNextButton: document.getElementById("paginationNextButton"),
  scopeFilterBar: document.getElementById("scopeFilterBar"),
  typeFilterBar: document.getElementById("typeFilterBar"),
  sizeFilterBar: document.getElementById("sizeFilterBar"),
  selectionCount: document.getElementById("selectionCount"),
  selectAllButton: document.getElementById("selectAllButton"),
  clearButton: document.getElementById("clearButton"),
  downloadButton: document.getElementById("downloadButton"),
  openWindowButton: document.getElementById("openWindowButton"),
  captureElementButton: document.getElementById("captureElementButton"),
  analyzeElementButton: document.getElementById("analyzeElementButton"),
  refreshButton: document.getElementById("refreshButton"),
  hideFixedStickyCheckbox: document.getElementById("hideFixedStickyCheckbox"),
  downloadLocationNote: document.getElementById("downloadLocationNote"),
  analysisPanel: document.getElementById("analysisPanel"),
  analysisSummary: document.getElementById("analysisSummary"),
  analysisOutput: document.getElementById("analysisOutput"),
  copyAnalysisButton: document.getElementById("copyAnalysisButton"),
  saveAnalysisButton: document.getElementById("saveAnalysisButton"),
  clearAnalysisButton: document.getElementById("clearAnalysisButton"),
  logList: document.getElementById("logList"),
  clearLogsButton: document.getElementById("clearLogsButton"),
  fullPageProgressPanel: document.getElementById("fullPageProgressPanel"),
  fullPageProgressBar: document.getElementById("fullPageProgressBar"),
  fullPageProgressText: document.getElementById("fullPageProgressText"),
  fullPageProgressStats: document.getElementById("fullPageProgressStats"),
  previewModal: document.getElementById("previewModal"),
  previewImage: document.getElementById("previewImage"),
  previewTitle: document.getElementById("previewTitle"),
  previewUrl: document.getElementById("previewUrl"),
  closePreviewButton: document.getElementById("closePreviewButton"),
};

export const urlParams = new URLSearchParams(window.location.search);

export const queryParamFlags = {
  hasHideFixedSticky: urlParams.has("hideFixedSticky"),
};
