export const elements = {
  statusMessage: document.getElementById("statusMessage"),
  segmentGeneralButton: document.getElementById("segmentGeneralButton"),
  segmentMockupButton: document.getElementById("segmentMockupButton"),
  segmentGeneralView: document.getElementById("segmentGeneralView"),
  segmentMockupView: document.getElementById("segmentMockupView"),
  mockupQuickAnalyzeButton: document.getElementById("mockupQuickAnalyzeButton"),
  mockupQuickCaptureButton: document.getElementById("mockupQuickCaptureButton"),
  mockupQuickZipButton: document.getElementById("mockupQuickZipButton"),
  sourceSite: document.getElementById("sourceSite"),
  sourceSiteValue: document.getElementById("sourceSiteValue"),
  imageList: document.getElementById("imageList"),
  paginationPanel: document.getElementById("paginationPanel"),
  paginationInfo: document.getElementById("paginationInfo"),
  paginationPrevButton: document.getElementById("paginationPrevButton"),
  paginationNextButton: document.getElementById("paginationNextButton"),
  scopeFilterBar: document.getElementById("scopeFilterBar"),
  typeFilterBar: document.getElementById("typeFilterBar"),
  sizeFilterBar: document.getElementById("sizeFilterBar"),
  selectionCount: document.getElementById("selectionCount"),
  selectAllButton: document.getElementById("selectAllButton"),
  clearButton: document.getElementById("clearButton"),
  downloadButton: document.getElementById("downloadButton"),
  openWindowButton: document.getElementById("openWindowButton"),
  captureElementButton: document.getElementById("captureElementButton"),
  analyzeElementButton: document.getElementById("analyzeElementButton"),
  refreshButton: document.getElementById("refreshButton"),
  hideFixedStickyCheckbox: document.getElementById("hideFixedStickyCheckbox"),
  downloadLocationNote: document.getElementById("downloadLocationNote"),
  analysisPanel: document.getElementById("analysisPanel"),
  analysisSummary: document.getElementById("analysisSummary"),
  analysisOutput: document.getElementById("analysisOutput"),
  analysisPreviewPanel: document.getElementById("analysisPreviewPanel"),
  analysisSvgPreview: document.getElementById("analysisSvgPreview"),
  analysisAssetGallery: document.getElementById("analysisAssetGallery"),
  analysisAssetList: document.getElementById("analysisAssetList"),
  copyAnalysisButton: document.getElementById("copyAnalysisButton"),
  saveAnalysisButton: document.getElementById("saveAnalysisButton"),
  downloadBlockBundleButton: document.getElementById("downloadBlockBundleButton"),
  clearAnalysisButton: document.getElementById("clearAnalysisButton"),
  logList: document.getElementById("logList"),
  clearLogsButton: document.getElementById("clearLogsButton"),
  previewModal: document.getElementById("previewModal"),
  previewImage: document.getElementById("previewImage"),
  previewTitle: document.getElementById("previewTitle"),
  previewUrl: document.getElementById("previewUrl"),
  closePreviewButton: document.getElementById("closePreviewButton"),
};

export const urlParams = new URLSearchParams(window.location.search);

export const queryParamFlags = {
  hasHideFixedSticky: urlParams.has("hideFixedSticky"),
};
